name: 'Ascend Notify install'
description: 'Ascend project GovuK Notify installer'
type: 'Site'
install:
  - govuk_notify
  - key
config:
  strict: true
  import:
    govuk_notify: '*'
    key: '*'
  actions:
    system.mail:
      simpleConfigUpdate:
        interface:
          govuk_notify: govuk_notify_mail
          # This sets the default system mail sender
          default: govuk_notify_mail
